### ISSUE TITLE
Pictures not loading on hover

### ISSUE THREAD

**Issue by BrickBlob** [rgriebl/brickstore#613]
A few updates back pictures are not loading when hovering a part or set etc. It does load the second time I try to hover though.

Other than that I noticed after last update that I can't confirm price using enter. I have to click ok.
I usually select all parts and press ctrl+g and hit enter.
Appears to happen because one of the drop downs are highlighted instead of the ok button.

I'm Windows 10 x64, computer is from 2009.

**Comment by ZZJHONS** [comment]
I can confirm both bugs.

Images not load until the second hover and OK is highlighted in blue but it is not in focus.

**Comment by BrickBlob** [comment]
Other than that! Great application! Couldn't live without it :)

**Comment by rgriebl** [comment]
> Other than that I noticed after last update that I can't confirm price using enter. I have to click ok.
> I usually select all parts and press ctrl+g and hit enter.
> Appears to happen because one of the drop downs are highlighted instead of the ok button.

I tracked this down to be a Qt bug: https://bugreports.qt.io/browse/QTBUG-107262 I've already fixed it upstream, so this should start working again, as soon as QT 6.4.1 is released (which is currently planned for Nov 15th)

**Comment by SteveTheBrick** [comment]
Both issues are fixed here on Win10.

**Comment by ZZJHONS** [comment]
Both work well here too on W11, now I can see (image is loading) for a second before the image appears correctly but the size seems still not so big as the info widget one, just a bit greater than the column one.

**Comment by rgriebl** [comment]
The image's size in the tooltip is the actual size of the image from BrickLink. All other images in BrickStore's UI are scaled to fit.
